### PR TITLE
Add mime type and filename as result for resolveContent

### PR DESCRIPTION
**Pull request by dickverweij**
I needed this plugin to respond on open file requests from the OS. 
But the original plugin did not provide filename and mimetype.

### CODE REVIEW

**Review by espresso3389 — CHANGES_REQUESTED** [review]
The new feature seems good but it breaks the compatibility.

Should we do major-update or keep the interface and add another method?

**Comment by dickverweij** [comment]
ok what do you suggest, as maintainer? My opion is on keep inteface, but i dont know how many users you have..
-- keep interface --
resolveContent -> buffer (old interface)
with extra resolveContentItem method -> ContentItem (new method to the interface)
-- major update --
resolveContent -> contentItem

**Comment by espresso3389** [comment]
OK, we should keep the interface.
`resolveContent` should be a thin wrapper of `resolveContentItem`, which just removes the extra fields.

**Comment by espresso3389** [comment]
After considering API compatibility, I finally dicided to break the API compatibility for better API surface; I mean it's too much to have two almost identical functions for such work.

And, I changed the `ContentItem` to `Content` and then updated comments for the document consistency.

**Comment by espresso3389** [comment]
[0.3.0](https://pub.dev/packages/content_resolver/versions/0.3.0) released.

**Comment by dickverweij** [comment]
> After considering API compatibility, I finally dicided to break the API compatibility for better API surface; I mean it's too much to have two almost identical functions for such work.
> 
> And, I changed the `ContentItem` to `Content` and then updated comments for the document consistency.

Great!

**Pull request merged**
